### ISSUE TITLE
Error setting state on unmounted component

### ISSUE THREAD

**Issue by romulof** [xtuc/async-reactor#17]
It the async promise resolves after the component has unmounted, React complains in red at the console.

You could just test inside the resolve callback if the component is mounted before calling `setState`:
```es6
if(this.isMounted()) {
  this.setState({...});
}
```
...but it is considered a bad practice:
https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html

So you might want to wrap that promise with `makeCancelable`.

**Comment by xtuc** [comment]
Yes, this sounds great, thanks for that. I'm working on it.

**Comment by xtuc** [comment]
I published the version 1.1.2 which removes the warning
