### ISSUE TITLE
Async Reactor's API is the future by the way

### ISSUE THREAD

**Issue by faceyspacey** [xtuc/async-reactor#21]
what u came up with here is just the beginning. 

Check this:

https://medium.com/@faceyspacey/code-cracked-for-code-splitting-ssr-in-reactlandia-react-loadable-webpack-flush-chunks-and-1a6b0112a8b8

And then read this:

https://github.com/faceyspacey/react-universal-component

the end of the readme extrapolates on your ideas to come up with a very idiomatic "universal rendering" solution using the API u invented. ..I gave you credit in a bunch of places too.

**Comment by xtuc** [comment]
Very nice, thanks!

I also think `async-reactor` has a simpler syntax, it seems less complicated.
